ALTER TABLE "StudyLog" ADD COLUMN "activityType" TEXT NOT NULL DEFAULT 'STUDY';
ALTER TABLE "StudyLog" ADD COLUMN "notes" TEXT;
ALTER TABLE "StudyLog" ADD COLUMN "difficulty" INTEGER;
ALTER TABLE "StudyModule" ADD COLUMN "goalMinutes" INTEGER NOT NULL DEFAULT 300;
